// <auto-generated />
namespace MrAng_Invoice.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class updateDB26 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(updateDB26));
        
        string IMigrationMetadata.Id
        {
            get { return "201802280512595_updateDB26"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
